services:
  ente-server:
    build:
      context: ente/server  # https://github.com/fourjr/ente-arm32v7.git#main:server
    image: fourjr/ente-server-arm32v7
    platform: linux/arm/v7

  minio:
    build:
      dockerfile: Dockerfile.minio
    image: fourjr/minio-arm32v7
    platform: linux/arm/v7

  minio-mc:
    build:
      dockerfile: Dockerfile.miniomc
    image: fourjr/minio-mc-arm32v7
    platform: linux/arm/v7
