FROM arm32v7/alpine

RUN apk add curl

RUN curl --silent --show-error --fail --location \
	--header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o /usr/bin/mc \
	"https://dl.min.io/client/mc/release/linux-arm/mc" \
	 && chmod 0755 /usr/bin/mc

EXPOSE 9000
ENTRYPOINT ["mc"]
VOLUME ["/export"]
